name: software-carpentries-scikit-hep-tutorial
channels:
  - conda-forge
dependencies:
  - hist==2.6.1
  - lz4==3.1.10
  - matplotlib==3.5.1
  - mplhep==0.3.23
  - numba==0.55.1
  - numpy==1.21.5
  - pandas==1.4.1
  - python=3.9
  - python-xxhash==3.0.0
  - xrootd==5.4.1
  - zstandard==0.17.0
  - pip==22.0.4
  - pip:
      - awkward==1.8.0
      - fastjet==3.3.4.0rc9
      - nlopt==2.7.0   # https://github.com/zfit/zfit/issues/387
      - particle==0.20.0
      - scikit-hep-testdata==0.4.12
      - uproot==4.2.2
      - vector==0.8.5
      - zfit==0.9.0a2
